name: RaB-pl
logo: "/assets/images/FLSmidth_logo.png" 
description: Operating-and-safety-instructions-for-split-sprocket-wheel
remote_theme: RAFBER/just-the-docs

color_scheme: light

aux_links:
  "Source repository on GitHub":
    - "//github.com//RAFBER.github.io"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "FLSmidth MAAG Gear Sp. z o.o. <br />
                 Stoczniowa 2 • 82-300 Elblag • Poland <br />
                 Tel +48 55 881 11 11 • Faks +48 55 881 11 12 <br />
                 mge@FLSmidthMaagGear.com • <a href=\"https://www.flsmidth.com/\">www.flsmidth.com</a>"

