name: RaB-pl
logo: "/assets/images/FLSmidth_logo.png" 
description: Operating-and-safety-instructions-for-split-sprocket-wheel
remote_theme: RAFBER/just-the-docs

color_scheme: light

aux_links:
  "Source repository on GitHub":
    - "//github.com/RAFBER/Operating-and-safety-instructions-for-split-sprocket-wheel"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "FLSmidth MAAG Gear Sp. z o.o. <br />
                 ul. Stoczniowa 2  <br />
          Tel +48 55 881 11 11 • Faks +48 55 881 11 12 <br />
          mge@FLSmidthMaagGear.com • www.FLSmidthMaagGear.com"

---
title: "Multi-line description set using Org Special Block (YAML)"
description: >
  Short description
  of this post


  **bold** -- _italics_ --- ~~strikethrough~~ `monospace`


  These lines <br />
  show up with line breaks <br />
  but within the same paragraph.
tags: ["front-matter", "description", "special-block", "yaml", "multi-line"]
draft: false
---

Post content.
